theme: jekyll-theme-minimal
title: Observability in a Box (OIB)
description: A plug-and-play observability stack for developers and homelabs. Clone, run, and get instant observability using Grafana's LGTM stack.
show_downloads: true
google_analytics:
baseurl: ""
